# Generated by Django 4.1.5 on 2023-01-04 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBufferWPChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20)),
                ('message_id', models.CharField(max_length=100)),
                ('message_type', models.CharField(max_length=50)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('media_link', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('message_status', models.CharField(max_length=10)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
