# Generated by Django 4.1.5 on 2023-01-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userbufferwpchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_text', models.TextField(blank=True)),
                ('output_text', models.TextField(blank=True, null=True)),
                ('openai_id', models.CharField(max_length=50)),
                ('openai_model', models.CharField(max_length=20)),
                ('openai_object', models.CharField(max_length=20)),
                ('completion_tokens', models.IntegerField()),
                ('prompt_tokens', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
