# Generated by Django 4.1.5 on 2023-01-08 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_openaianswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StableDiffusionImageGeneration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=100)),
                ('message_text', models.TextField()),
                ('number_of_images', models.PositiveIntegerField()),
                ('image_size', models.PositiveIntegerField()),
                ('image_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('image_name', models.CharField(max_length=50)),
                ('image_path', models.FileField(max_length=80, upload_to='generated_images/')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
