# Generated by Django 4.1.5 on 2023-01-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stablediffusionimagegeneration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stablediffusionimagegeneration',
            name='image_path',
            field=models.FileField(max_length=150, upload_to='generated_images/'),
        ),
    ]
