# Generated by Django 4.1.5 on 2023-01-04 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EachTokenMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.PositiveIntegerField(default=1)),
                ('other_character', models.DecimalField(decimal_places=7, default=1, max_digits=10)),
                ('whatsapp_character', models.DecimalField(decimal_places=7, default=0.6, max_digits=10)),
                ('image', models.DecimalField(decimal_places=7, default=0.00025, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=20)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.DecimalField(decimal_places=7, max_digits=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_used', models.DecimalField(decimal_places=7, max_digits=20)),
                ('used_paltform', models.CharField(max_length=20)),
                ('message_id', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile')),
            ],
        ),
    ]
