# Generated by Django 4.1.5 on 2023-01-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_is_password_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
