# Generated by Django 4.1.5 on 2023-01-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokenbalance',
            name='token_threshold',
            field=models.DecimalField(decimal_places=7, default=100.0, max_digits=20),
        ),
    ]
