# Generated by Django 4.1.5 on 2023-01-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_usertokenbalance_token_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='remaining_tokens',
            field=models.DecimalField(decimal_places=7, default=100.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='eachtokenmap',
            name='whatsapp_character',
            field=models.DecimalField(decimal_places=7, default=1.6, max_digits=10),
        ),
    ]
