# Generated by Django 4.1.5 on 2023-01-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_usertokenbalance_image_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(max_length=150, null=True, upload_to='profile_images/'),
        ),
    ]
