# Generated by Django 4.1.5 on 2023-01-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
